In [92]:
import pandas as pd 
import numpy as np

In [93]:
df = pd.read_csv('loan_approval_dataset.csv')

In [94]:
df.shape

(4269, 13)

In [95]:
df.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [96]:
df.columns

Index(['loan_id', ' no_of_dependents', ' education', ' self_employed',
       ' income_annum', ' loan_amount', ' loan_term', ' cibil_score',
       ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value', ' loan_status'],
      dtype='object')

In [97]:
df.drop(columns=['loan_id'],inplace = True)

In [98]:
df.columns =  df.columns.str.strip()

In [99]:
df

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected
...,...,...,...,...,...,...,...,...,...,...,...,...
4264,5,Graduate,Yes,1000000,2300000,12,317,2800000,500000,3300000,800000,Rejected
4265,0,Not Graduate,Yes,3300000,11300000,20,559,4200000,2900000,11000000,1900000,Approved
4266,2,Not Graduate,No,6500000,23900000,18,457,1200000,12400000,18100000,7300000,Rejected
4267,1,Not Graduate,No,4100000,12800000,8,780,8200000,700000,14100000,5800000,Approved
4268,1,Graduate,No,9200000,29700000,10,607,17800000,11800000,35700000,12000000,Approved

In [100]:
df.columns

Index(['no_of_dependents', 'education', 'self_employed', 'income_annum',
       'loan_amount', 'loan_term', 'cibil_score', 'residential_assets_value',
       'commercial_assets_value', 'luxury_assets_value', 'bank_asset_value',
       'loan_status'],
      dtype='object')

In [101]:
df['assets'] = df.residential_assets_value + df.residential_assets_value + df.luxury_assets_value + df.bank_asset_value

In [102]:
df

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status,assets
0,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved,35500000
1,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected,17500000
2,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected,60300000
3,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected,67600000
4,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected,59200000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4264,5,Graduate,Yes,1000000,2300000,12,317,2800000,500000,3300000,800000,Rejected,9700000
4265,0,Not Graduate,Yes,3300000,11300000,20,559,4200000,2900000,11000000,1900000,Approved,21300000
4266,2,Not Graduate,No,6500000,23900000,18,457,1200000,12400000,18100000,7300000,Rejected,27800000
4267,1,Not Graduate,No,4100000,12800000,8,780,8200000,700000,14100000,5800000,Approved,36300000
4268,1,Graduate,No,9200000,29700000,10,607,17800000,11800000,35700000,12000000,Approved,83300000

In [103]:
df.drop(columns=['residential_assets_value','commercial_assets_value','luxury_assets_value','bank_asset_value'],inplace=True)

In [104]:
df

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,loan_status,assets
0,2,Graduate,No,9600000,29900000,12,778,Approved,35500000
1,0,Not Graduate,Yes,4100000,12200000,8,417,Rejected,17500000
2,3,Graduate,No,9100000,29700000,20,506,Rejected,60300000
3,3,Graduate,No,8200000,30700000,8,467,Rejected,67600000
4,5,Not Graduate,Yes,9800000,24200000,20,382,Rejected,59200000
...,...,...,...,...,...,...,...,...,...
4264,5,Graduate,Yes,1000000,2300000,12,317,Rejected,9700000
4265,0,Not Graduate,Yes,3300000,11300000,20,559,Approved,21300000
4266,2,Not Graduate,No,6500000,23900000,18,457,Rejected,27800000
4267,1,Not Graduate,No,4100000,12800000,8,780,Approved,36300000
4268,1,Graduate,No,9200000,29700000,10,607,Approved,83300000

In [105]:
df.isnull().sum()

no_of_dependents    0
education           0
self_employed       0
income_annum        0
loan_amount         0
loan_term           0
cibil_score         0
loan_status         0
assets              0
dtype: int64

In [106]:
df.education.unique()

array([' Graduate', ' Not Graduate'], dtype=object)

In [107]:
def clean_data(st):
    st = st.strip()
    return st

In [108]:
clean_data(' Graduate ')

'Graduate'

In [109]:
df.education = df.education.apply(clean_data)

In [110]:
df.education.unique()

array(['Graduate', 'Not Graduate'], dtype=object)

In [111]:
df['education']=df.education.replace(['Graduate','Not Graduate'],[1,0])

/var/folders/yt/m3t63_md6313mdtp_6bbphtw0000gn/T/ipykernel_31731/2836656986.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['education']=df.education.replace(['Graduate','Not Graduate'],[1,0])

In [112]:
df.education

0       1
1       0
2       1
3       1
4       0
       ..
4264    1
4265    0
4266    0
4267    0
4268    1
Name: education, Length: 4269, dtype: int64

In [113]:
df

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,loan_status,assets
0,2,1,No,9600000,29900000,12,778,Approved,35500000
1,0,0,Yes,4100000,12200000,8,417,Rejected,17500000
2,3,1,No,9100000,29700000,20,506,Rejected,60300000
3,3,1,No,8200000,30700000,8,467,Rejected,67600000
4,5,0,Yes,9800000,24200000,20,382,Rejected,59200000
...,...,...,...,...,...,...,...,...,...
4264,5,1,Yes,1000000,2300000,12,317,Rejected,9700000
4265,0,0,Yes,3300000,11300000,20,559,Approved,21300000
4266,2,0,No,6500000,23900000,18,457,Rejected,27800000
4267,1,0,No,4100000,12800000,8,780,Approved,36300000
4268,1,1,No,9200000,29700000,10,607,Approved,83300000

In [114]:
df['loan_status'].unique()

array([' Approved', ' Rejected'], dtype=object)

In [115]:
df.loan_status = df.loan_status.apply(clean_data)
df['loan_status']=df.loan_status.replace(['Approved','Rejected'],[1,0])

/var/folders/yt/m3t63_md6313mdtp_6bbphtw0000gn/T/ipykernel_31731/3113586443.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['loan_status']=df.loan_status.replace(['Approved','Rejected'],[1,0])

In [116]:
df

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,loan_status,assets
0,2,1,No,9600000,29900000,12,778,1,35500000
1,0,0,Yes,4100000,12200000,8,417,0,17500000
2,3,1,No,9100000,29700000,20,506,0,60300000
3,3,1,No,8200000,30700000,8,467,0,67600000
4,5,0,Yes,9800000,24200000,20,382,0,59200000
...,...,...,...,...,...,...,...,...,...
4264,5,1,Yes,1000000,2300000,12,317,0,9700000
4265,0,0,Yes,3300000,11300000,20,559,1,21300000
4266,2,0,No,6500000,23900000,18,457,0,27800000
4267,1,0,No,4100000,12800000,8,780,1,36300000
4268,1,1,No,9200000,29700000,10,607,1,83300000

In [117]:
df.self_employed = df.self_employed.apply(clean_data)

In [118]:
df['self_employed']=df.self_employed.replace(['Yes','No'],[1,0])

/var/folders/yt/m3t63_md6313mdtp_6bbphtw0000gn/T/ipykernel_31731/1245288497.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['self_employed']=df.self_employed.replace(['Yes','No'],[1,0])

In [119]:
df

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,loan_status,assets
0,2,1,0,9600000,29900000,12,778,1,35500000
1,0,0,1,4100000,12200000,8,417,0,17500000
2,3,1,0,9100000,29700000,20,506,0,60300000
3,3,1,0,8200000,30700000,8,467,0,67600000
4,5,0,1,9800000,24200000,20,382,0,59200000
...,...,...,...,...,...,...,...,...,...
4264,5,1,1,1000000,2300000,12,317,0,9700000
4265,0,0,1,3300000,11300000,20,559,1,21300000
4266,2,0,0,6500000,23900000,18,457,0,27800000
4267,1,0,0,4100000,12800000,8,780,1,36300000
4268,1,1,0,9200000,29700000,10,607,1,83300000

In [120]:
from sklearn.model_selection import train_test_split

In [121]:
input_data = df.drop(columns=['loan_status'])
output_data = df['loan_status']

In [122]:
input_data

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,assets
0,2,1,0,9600000,29900000,12,778,35500000
1,0,0,1,4100000,12200000,8,417,17500000
2,3,1,0,9100000,29700000,20,506,60300000
3,3,1,0,8200000,30700000,8,467,67600000
4,5,0,1,9800000,24200000,20,382,59200000
...,...,...,...,...,...,...,...,...
4264,5,1,1,1000000,2300000,12,317,9700000
4265,0,0,1,3300000,11300000,20,559,21300000
4266,2,0,0,6500000,23900000,18,457,27800000
4267,1,0,0,4100000,12800000,8,780,36300000
4268,1,1,0,9200000,29700000,10,607,83300000

In [123]:
output_data

0       1
1       0
2       0
3       0
4       0
       ..
4264    0
4265    1
4266    0
4267    1
4268    1
Name: loan_status, Length: 4269, dtype: int64

In [124]:
x_train,x_test,y_train,y_test = train_test_split(input_data,output_data,test_size=0.2)

In [125]:
print(x_train.shape , x_test.shape , y_train.shape , y_test.shape)

(3415, 8) (854, 8) (3415,) (854,)

In [126]:
from sklearn.preprocessing import StandardScaler

In [127]:
scaler = StandardScaler()

In [128]:
x_train_scaled =  scaler1.fit_transform(x_train)

In [129]:
x_test_scaled = scaler1.fit(x_test)

In [130]:
from sklearn.linear_model import LogisticRegression

In [131]:
model = LogisticRegression()

In [132]:
model.fit(x_train_scaled,y_train)

LogisticRegression()

In [133]:
prediction = model.predict(x_train_scaled)

In [134]:
model.score(x_test,y_test)

/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py:432: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(

0.6334894613583139

In [135]:
x_test_scaled = scaler1.transform(x_test)

In [136]:
model.score(x_test_scaled,y_test)

0.9168618266978923

In [137]:
import pickle as pk

In [138]:
pk.dump(model,open('model.pkl','wb'))

In [139]:
pk.dump(model,open('scaler.pkl','wb'))

In [140]:
with open("scaler.pkl", "wb") as f:
    pk.dump(scaler, f)

with open("model.pkl", "wb") as f:
    pk.dump(model, f)

In [141]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(x_train)  


model = LogisticRegression()
model.fit(X_scaled, y_train)


with open("scaler.pkl", "wb") as f:
    pk.dump(scaler, f)

with open("model.pkl", "wb") as f:
    pk.dump(model, f)